[package]
name = "tls-listener"
version = "0.1.0"
authors = ["Thayne McCombs <astrothayne@gmail.com>"]
repository = "https://github.com/tmccombs/tls-listener"
edition = "2018"

[dependencies]
futures = "0.1.25"
native-tls = "0.2"
tokio-executor = "0.1.6"
tokio-io = "0.1.11"
tokio-tls = "0.2.1"

[dev-dependencies]
hyper = "0.12.23"
tokio = "0.1.15"
