name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        tls: [rustls, native-tls]
        features:
          - hyper-h1,hyper-h2
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: Build
        run: cargo build --verbose --examples --features ${{ matrix.tls }},${{ matrix.features }}
      - name: Test
        run: cargo test --verbose --features ${{ matrix.tls }},${{ matrix.features }}
      - name: Lint
        run: cargo clippy --examples --features ${{ matrix.tls }},${{ matrix.features }}
      - name: Format check
        run: cargo fmt -- --check
