name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:

jobs:
  build-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: Build
        run: cargo build --verbose --examples --all-features
      - name: Test
        run: cargo test --verbose --all-features
      - name: Lint
        run: cargo clippy --examples --all-features
      - name: Format check
        run: cargo fmt -- --check
  check-features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - ""
          - tokio-net
          - rustls
          - native-tls
          - openssl
          - rt
          - hyper-h1
          - hyper-h2
          - rustls,native-tls,openssl
          - tokio-net,rt,rustls
          - tokio-net,native-tls
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Check
        run: cargo check --verbose --no-default-features --features "${{ matrix.features }}"
